Repository lotte-team6-onthefarm/OnAndTheFarm-ProductService, pull requests merged in 2022-11, with the labels that each got.

#38 feat : nudge를 위한 feedNumber 추가
  src/main/java/com/team6/onandthefarmproductservice/controller/UserProductController.java
  src/main/java/com/team6/onandthefarmproductservice/service/ProductService.java
  src/main/java/com/team6/onandthefarmproductservice/service/ProductServiceImpl.java
  src/main/java/com/team6/onandthefarmproductservice/vo/product/ProductDetailResponse.java
Labels: feat

#39 fix: swagger 설정 추가
  src/main/java/com/team6/onandthefarmproductservice/config/SecurityConfig.java
  src/main/java/com/team6/onandthefarmproductservice/config/SwaggerConfig.java
  src/main/java/com/team6/onandthefarmproductservice/controller/CartController.java
  src/main/java/com/team6/onandthefarmproductservice/controller/UserProductController.java
Labels: fix

#41 feat: 써킷브레이커 구현 / user 질의 조회 페이지네이션 구현
  build.gradle
  src/main/java/com/team6/onandthefarmproductservice/config/Resilience4JConfig.java
  src/main/java/com/team6/onandthefarmproductservice/controller/UserProductController.java
  src/main/java/com/team6/onandthefarmproductservice/feignclient/UserServiceClient.java
  src/main/java/com/team6/onandthefarmproductservice/feignclient/vo/UserVo.java
  src/main/java/com/team6/onandthefarmproductservice/service/ProductService.java
  src/main/java/com/team6/onandthefarmproductservice/service/ProductServiceImpl.java
  src/main/java/com/team6/onandthefarmproductservice/service/ReviewServiceImpl.java
  src/main/java/com/team6/onandthefarmproductservice/vo/product/ProductQnAResponseResult.java
Labels: feat, fix

#42 feat : cart, review pagination
  src/main/java/com/team6/onandthefarmproductservice/controller/CartController.java
  src/main/java/com/team6/onandthefarmproductservice/controller/SellerReviewController.java
  src/main/java/com/team6/onandthefarmproductservice/controller/UserReviewController.java
  src/main/java/com/team6/onandthefarmproductservice/repository/ReviewPagingRepository.java
  src/main/java/com/team6/onandthefarmproductservice/service/CartService.java
  src/main/java/com/team6/onandthefarmproductservice/service/CartServiceImpl.java
  src/main/java/com/team6/onandthefarmproductservice/service/ProductServiceImpl.java
  src/main/java/com/team6/onandthefarmproductservice/service/ReviewServiceImpl.java
  src/main/java/com/team6/onandthefarmproductservice/vo/cart/CartResult.java
  src/main/java/com/team6/onandthefarmproductservice/vo/product/ProductQnAInfoResponse.java
  src/main/java/com/team6/onandthefarmproductservice/vo/product/ProductQnAResponseResult.java
Labels: feat

#43 feat: zipkin 의존성 추가:
  build.gradle
Labels: feat

#44 fix: @Request param으로 변경(@RequestBody를) / feignClient부분의 rul 수정
  src/main/java/com/team6/onandthefarmproductservice/feignclient/OrderServiceClient.java
  src/main/java/com/team6/onandthefarmproductservice/repository/ReviewPagingRepository.java
Labels: fix

#45 fix: seller mypage 조회 시 리뷰,인기상품에 productId 추가
  src/main/java/com/team6/onandthefarmproductservice/service/ProductServiceImpl.java
  src/main/java/com/team6/onandthefarmproductservice/vo/product/SellerPopularProductResponse.java
  src/main/java/com/team6/onandthefarmproductservice/vo/product/SellerRecentReviewResponse.java
Labels: fix

#46 fix : wish 부분조회 로직 수정
  src/main/java/com/team6/onandthefarmproductservice/feignclient/controller/ProductServiceClientControllerEX.java
Labels: fix

#47 fix: qna 리스트를 불러올때 response값에 상품 이미지, 상품 이름을 추가
  src/main/java/com/team6/onandthefarmproductservice/service/ProductServiceImpl.java
  src/main/java/com/team6/onandthefarmproductservice/vo/product/ProductQnAResponse.java
Labels: fix

#48 fix : wish 로직 수정
  src/main/java/com/team6/onandthefarmproductservice/feignclient/controller/ProductServiceClientControllerEX.java
  src/main/java/com/team6/onandthefarmproductservice/feignclient/service/ProductServiceClientServiceEX.java
  src/main/java/com/team6/onandthefarmproductservice/feignclient/service/ProductServiceClientServiceImpEX.java
Labels: fix

#49 fix: 성능향상을 위한 exist쿼리 수
  src/main/java/com/team6/onandthefarmproductservice/feignclient/service/ProductServiceClientServiceImpEX.java
  src/main/java/com/team6/onandthefarmproductservice/kafka/KafkaConsumerConfig.java
  src/main/java/com/team6/onandthefarmproductservice/repository/CartRepository.java
  src/main/java/com/team6/onandthefarmproductservice/repository/ProductWishRepository.java
  src/main/java/com/team6/onandthefarmproductservice/repository/ReservedOrderRepository.java
  src/main/java/com/team6/onandthefarmproductservice/service/ProductServiceImpl.java
Labels: fix

#50 fix: 멱등 수신자를 위한 로직 수정
  src/main/java/com/team6/onandthefarmproductservice/kafka/ProductOrderChannelAdapterKafkaImpl.java
  src/main/java/com/team6/onandthefarmproductservice/repository/ReservedOrderRepository.java
  src/main/java/com/team6/onandthefarmproductservice/service/ProductService.java
  src/main/java/com/team6/onandthefarmproductservice/service/ProductServiceImpl.java
Labels: fix

#51 feat : admin security 추가
  src/main/java/com/team6/onandthefarmproductservice/config/SecurityConfig.java
  src/main/java/com/team6/onandthefarmproductservice/security/JwtAuthenticationFilter.java
Labels: feat

#52 fix : seller qna 조회 시 에러 수정
  src/main/java/com/team6/onandthefarmproductservice/repository/ProductQnaRepository.java
  src/main/java/com/team6/onandthefarmproductservice/service/ProductServiceImpl.java
Labels: fix

#53 fix: feignclient 인증 관련 수정 및 셀러 오피스 인기 상품 사진 수정
  src/main/java/com/team6/onandthefarmproductservice/config/SecurityConfig.java
  src/main/java/com/team6/onandthefarmproductservice/service/ProductServiceImpl.java
Labels: fix

#54 fix: security 추가 및 feign용 url 수정
  src/main/java/com/team6/onandthefarmproductservice/config/SecurityConfig.java
  src/main/java/com/team6/onandthefarmproductservice/feignclient/OrderServiceClient.java
  src/main/java/com/team6/onandthefarmproductservice/feignclient/SellerServiceClient.java
  src/main/java/com/team6/onandthefarmproductservice/feignclient/UserServiceClient.java
  src/main/java/com/team6/onandthefarmproductservice/feignclient/controller/ProductServiceClientControllerEX.java
  src/main/java/com/team6/onandthefarmproductservice/feignclient/controller/SnsServiceClientController.java
Labels: fix

#55 feat : exhibitionService Client 구현
  src/main/java/com/team6/onandthefarmproductservice/feignclient/controller/ProductServiceClientControllerEX.java
  src/main/java/com/team6/onandthefarmproductservice/feignclient/service/ProductServiceClientServiceEX.java
  src/main/java/com/team6/onandthefarmproductservice/feignclient/service/ProductServiceClientServiceImpEX.java
  src/main/java/com/team6/onandthefarmproductservice/feignclient/vo/ReviewInfoToExbt.java
Labels: feat

#56 fix: seller페이지의 재고부족상품 조회 수정
  src/main/java/com/team6/onandthefarmproductservice/repository/ProductPagingRepository.java
Labels: fix

#57 feat : productPaging 수정
  src/main/java/com/team6/onandthefarmproductservice/repository/ProductPagingRepository.java
Labels: fix

#58 feat : findProductBySellerId 수정
  src/main/java/com/team6/onandthefarmproductservice/repository/ProductRepository.java
Labels: fix

#59 feat: kafka sink를 위한 데이터 수정
  src/main/java/com/team6/onandthefarmproductservice/ParticipantLink.java
  src/main/java/com/team6/onandthefarmproductservice/entity/ReservedOrder.java
  src/main/java/com/team6/onandthefarmproductservice/feignclient/controller/ProductServiceClientControllerEX.java
  src/main/java/com/team6/onandthefarmproductservice/feignclient/service/ProductServiceClientServiceImpEX.java
Labels: feat

#60 feat: 재고차감에 대한 kafka sink 구현
  src/main/java/com/team6/onandthefarmproductservice/entity/ReservedOrder.java
  src/main/java/com/team6/onandthefarmproductservice/feignclient/controller/ProductServiceClientControllerEX.java
  src/main/java/com/team6/onandthefarmproductservice/feignclient/service/ProductServiceClientServiceEX.java
  src/main/java/com/team6/onandthefarmproductservice/feignclient/service/ProductServiceClientServiceImpEX.java
  src/main/java/com/team6/onandthefarmproductservice/kafka/vo/Field.java
  src/main/java/com/team6/onandthefarmproductservice/kafka/vo/KafkaOrderDto.java
  src/main/java/com/team6/onandthefarmproductservice/kafka/vo/Payload.java
  src/main/java/com/team6/onandthefarmproductservice/kafka/vo/Schema.java
  src/main/java/com/team6/onandthefarmproductservice/repository/ReservedOrderRepository.java
  src/main/java/com/team6/onandthefarmproductservice/service/ProductServiceImpl.java
Labels: feat

#61 feat : elastic search product document entity 추가
  src/main/java/com/team6/onandthefarmproductservice/entity/ProductDocument.java
Labels: feat

#62 fix: 엘라스틱서치 의존성추가 및 패키지명 수정
  build.gradle
  src/main/java/com/team6/onandthefarmproductservice/entity/ProductDocument.java
Labels: fix

#63 fix: product document entity 추가
  src/main/java/com/team6/onandthefarmproductservice/entity/ProductDocument.java
Labels: fix

#64 fix : security 오류 해결
  src/main/java/com/team6/onandthefarmproductservice/config/SecurityConfig.java
Labels: fix

#65 fix: tcc timeout 부분 수정
  src/main/java/com/team6/onandthefarmproductservice/entity/ReservedOrder.java
  src/main/java/com/team6/onandthefarmproductservice/feignclient/service/ProductServiceClientServiceImpEX.java
Labels: fix

#66 fix: 한국 날짜로 시간 변경
  src/main/java/com/team6/onandthefarmproductservice/util/DateUtils.java
Labels: fix
